### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [2]:
import numpy as np   # Imports the numpy module and call it as np

A = np.array([[i for i in range(1, 101)]])  # I used list comprehension to generate values from 1 to 100.

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.

In [6]:
# Creates a four-dimensional array of random integers in the interval [0, 12]
random_array = np.random.randint(0, 15, size=(3, 4, 5, 6))

# Prints the resulting array
print("Four-dimensional array of random integers:")
print(random_array)

Four-dimensional array of random integers:
[[[[12  7  9  6  6  3]
   [13  0 10  5  5  5]
   [10  9 12  3  3 13]
   [ 9  1  5  1  3  3]
   [ 9 13  9  7  2  3]]

  [[ 8 13 13  0  2 10]
   [ 2 10  3  4  2  3]
   [ 9  2  6 14 13  5]
   [ 4 11 13  2  1  7]
   [ 2 11  6  5  1 14]]

  [[ 6  8  5  2  5  5]
   [ 0 11 11 13 11 13]
   [ 7  4  7 10  1 10]
   [ 3  3  0  5  0 13]
   [14  1 11  8 13  4]]

  [[11  4 12 11 10  5]
   [ 1 12  1 11  8 12]
   [ 1 10  1 12 14  8]
   [10  8 12 12  9  5]
   [ 0 12 12  8  0  3]]]


 [[[ 7  5  1  5  4  9]
   [ 9  2  9  7 14 10]
   [12  8  1  2 11 13]
   [ 4 10  5  0  3 11]
   [14 13  4 11  3  7]]

  [[ 4 12 12  3  4 11]
   [14  5 12 10 13  1]
   [ 8  8 11  4 13  0]
   [ 5  6 14 11  2 10]
   [ 7  6  7  1  4  8]]

  [[ 7  7  5 14 10  0]
   [ 3  9 13 14  5  7]
   [ 1  5  0  1  4  2]
   [ 2 10  1  7 13 13]
   [ 2  2  9 12  1 12]]

  [[10  3  9 12 11  8]
   [ 3 14  1  3  0  7]
   [ 4 13  7  3 11  1]
   [14  7  1  7  9 12]
   [13 14  6  0 10 12]]]


 [[[10  1  9  6  

B. Get the maximum number for each dimensions and display it.

In [7]:
# Get the maximum number for each dimension
max_per_dimension = random_array.max(axis=(0, 1, 2, 3))

# Displays the maximum number for each dimension
print("Maximum number for each dimension:")
print(max_per_dimension)

Maximum number for each dimension:
14


C. Multipy each array with 4. What is its result? * Write a brief explanation on the multiplication process.

In [9]:
# Multiplies each array element by 4. Each element in the array random_array is multiplied by 4, resulting in a new array result where each element is four times its original value.
result = random_array * 4

# Displays the result
print("Result: ")
print(result)

Result after multiplying each array element by 4:
[[[[48 28 36 24 24 12]
   [52  0 40 20 20 20]
   [40 36 48 12 12 52]
   [36  4 20  4 12 12]
   [36 52 36 28  8 12]]

  [[32 52 52  0  8 40]
   [ 8 40 12 16  8 12]
   [36  8 24 56 52 20]
   [16 44 52  8  4 28]
   [ 8 44 24 20  4 56]]

  [[24 32 20  8 20 20]
   [ 0 44 44 52 44 52]
   [28 16 28 40  4 40]
   [12 12  0 20  0 52]
   [56  4 44 32 52 16]]

  [[44 16 48 44 40 20]
   [ 4 48  4 44 32 48]
   [ 4 40  4 48 56 32]
   [40 32 48 48 36 20]
   [ 0 48 48 32  0 12]]]


 [[[28 20  4 20 16 36]
   [36  8 36 28 56 40]
   [48 32  4  8 44 52]
   [16 40 20  0 12 44]
   [56 52 16 44 12 28]]

  [[16 48 48 12 16 44]
   [56 20 48 40 52  4]
   [32 32 44 16 52  0]
   [20 24 56 44  8 40]
   [28 24 28  4 16 32]]

  [[28 28 20 56 40  0]
   [12 36 52 56 20 28]
   [ 4 20  0  4 16  8]
   [ 8 40  4 28 52 52]
   [ 8  8 36 48  4 48]]

  [[40 12 36 48 44 32]
   [12 56  4 12  0 28]
   [16 52 28 12 44  4]
   [56 28  4 28 36 48]
   [52 56 24  0 40 48]]]


 [[[40  4 